name = "Matches"
uuid = "cc7bb1c6-c516-4f87-8bff-2b03ea31ba11"
authors = ["ForceBru <ForceBru@users.noreply.github.com>"]
version = "0.1.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
